# Create Decade Sankey Plots for Decision Analysis Methods
# Uses the existing plot_sankey.R function to create simple decade-by-decade visualizations

library(jsonlite)

# Source the existing plot_sankey function
source("R/plot_sankey.R")

# Read the sankey data generated by Python
sankey_data <- fromJSON("sankey_data.json")

# Function to create a simple Sankey for one decade
create_decade_sankey <- function(decade_name, decade_data) {
  total_papers <- decade_data$total_papers
  methods <- decade_data$methods

  # Skip decades with too few papers
  if (total_papers < 50) {
    return(NULL)
  }

  # Get top methods (sorted by count)
  method_counts <- unlist(methods)
  method_counts <- method_counts[method_counts > 0]
  method_counts <- sort(method_counts, decreasing = TRUE)

  # Take top 5-7 methods for clarity
  top_methods <- head(method_counts, 7)

  # Calculate remaining papers
  papers_with_methods <- sum(top_methods)
  papers_without_methods <- total_papers - papers_with_methods

  # Prepare data for plot_sankey function
  inputs <- total_papers
  losses <- c(as.numeric(top_methods), papers_without_methods)
  unit <- "papers"

  # Create labels
  method_names <- names(top_methods)
  # Shorten long method names for clarity
  method_names <- gsub("Multi-Criteria Decision Analysis", "MCDA", method_names)
  method_names <- gsub("Expert Systems and AI", "Expert Systems/AI", method_names)
  method_names <- gsub("Decision Trees and Networks", "Decision Trees", method_names)
  method_names <- gsub("Behavioral Decision Theory", "Behavioral Theory", method_names)
  method_names <- gsub("Delphi and Expert Judgment", "Delphi/Expert", method_names)

  labels <- c(paste(decade_name, "Total"), method_names, "No Specific Methods")

  # Create the plot
  plot_sankey(
    inputs = inputs,
    losses = losses,
    unit = unit,
    labels = labels,
    format = "pdf"
  )

  # Rename the generated file
  if (file.exists("Sankey.pdf")) {
    new_name <- paste0("sankey_", gsub("s$", "", tolower(decade_name)), ".pdf")
    file.rename("Sankey.pdf", new_name)
    cat("Created:", new_name, "\n")
  }

  # Also create PNG version for easier viewing
  plot_sankey(
    inputs = inputs,
    losses = losses,
    unit = unit,
    labels = labels,
    format = "bmp"
  )

  if (file.exists("Sankey.bmp")) {
    new_name <- paste0("sankey_", gsub("s$", "", tolower(decade_name)), ".bmp")
    file.rename("Sankey.bmp", new_name)
    cat("Created:", new_name, "\n")
  }

  # Return summary info
  return(list(
    decade = decade_name,
    total_papers = total_papers,
    method_papers = papers_with_methods,
    top_methods = top_methods
  ))
}

# Main execution
cat("Creating decade-by-decade Sankey plots using plot_sankey.R\n")
cat(rep("=", 60), "\n")

# Get decades with substantial data
decades_to_plot <- names(sankey_data)[sapply(sankey_data, function(x) x$total_papers >= 50)]
decades_to_plot <- sort(decades_to_plot)

# Create plots for each decade
results <- list()
for (decade in decades_to_plot) {
  cat("\nProcessing", decade, "...\n")

  result <- create_decade_sankey(decade, sankey_data[[decade]])
  if (!is.null(result)) {
    results[[decade]] <- result

    # Print summary
    cat(sprintf("  Total papers: %d\n", result$total_papers))
    cat(sprintf(
      "  Papers with methods: %d (%.1f%%)\n",
      result$method_papers,
      (result$method_papers / result$total_papers) * 100
    ))
    cat("  Top methods:\n")
    for (i in seq_along(result$top_methods)) {
      method_name <- names(result$top_methods)[i]
      method_count <- result$top_methods[[i]]
      cat(sprintf("    %s: %d papers\n", method_name, method_count))
    }
  }
}

cat("\n", rep("=", 60), "\n")
cat("Summary of all decades:\n")

total_all_papers <- sum(sapply(results, function(x) x$total_papers))
total_method_papers <- sum(sapply(results, function(x) x$method_papers))

cat(sprintf("Total papers across all plotted decades: %d\n", total_all_papers))
cat(sprintf(
  "Papers with identified methods: %d (%.1f%%)\n",
  total_method_papers,
  (total_method_papers / total_all_papers) * 100
))

# Aggregate top methods across all decades
all_methods <- list()
for (result in results) {
  for (method in names(result$top_methods)) {
    if (method %in% names(all_methods)) {
      all_methods[[method]] <- all_methods[[method]] + result$top_methods[[method]]
    } else {
      all_methods[[method]] <- result$top_methods[[method]]
    }
  }
}

# Sort and display overall top methods
all_methods <- sort(unlist(all_methods), decreasing = TRUE)
cat("\nTop methods across all decades:\n")
for (i in 1:min(8, length(all_methods))) {
  method_name <- names(all_methods)[i]
  method_count <- all_methods[[i]]
  percentage <- (method_count / total_all_papers) * 100
  cat(sprintf("  %s: %d papers (%.1f%%)\n", method_name, method_count, percentage))
}

cat("\nFiles created:")
for (decade in decades_to_plot) {
  decade_short <- gsub("s$", "", tolower(decade))
  cat(sprintf("\n  sankey_%s.pdf", decade_short))
  cat(sprintf("\n  sankey_%s.bmp", decade_short))
}

cat("\n\nAll decade Sankey plots completed!\n")
